### ISSUE TITLE
Rooms where specific products are sold

### ISSUE THREAD

**Issue by VirtualSatai** [f-klubben/stregsystemet#19] opened 2017-03-15 14:20 UTC
For example foobar only sells beer.

**Comment by jones-g** [comment] 2017-03-22 15:54
Please look at f-klubben/stregsystem#10 for a discussion on rooms/views etc.

**Comment by DelusionalLogic** [comment] 2017-09-28 11:11
Did #93 Solve this. Or do you have any other requirements?

**Comment by hrjakobsen** [comment] 2017-09-28 17:43
If the usecase is to have a room where only a specific set of products are sold, there could be some boolean value on a room indicating if it should be possible to buy the regular stock as well.

For example:
If FooBar have the regular stock disabled, you will only see "Fadøl" as an option in stregsystemet, but if the regular stock is enabled, you will see the regular stock as well as "Fadøl".

**Comment by DelusionalLogic** [comment] 2017-09-28 21:17
At that point you're talking about adding another layer of indirection between rooms and "product ranges". I don't think that's necessary at this time, So i vote we close this and we can open another issue if something changes and the added complexity becomes valuable.

**Comment by Rene4100** [comment] 2017-11-08 09:31
For a TREO perspective, I see this issue as already solved in a previous PR.
I suggest that the issue is marked as a duplicate and then close the issue

**Closed** 2017-11-08 09:55 UTC
Labels: enhancement
