### ISSUE TITLE
Can access other peoples login

### ISSUE THREAD

**Issue by LucasWedel** [f-klubben/stregsystemet#345] opened 2023-08-22 07:21 UTC
Does not feel super safe, that it is possible to access other users logins by changing the url: (https://stregsystem.fklub.dk/10/sale/xxxx/).

If you swap out xxxx with any number, fx. 4444 (https://stregsystem.fklub.dk/10/sale/4444/).

Then you will land on a random persons login, where it is possible to order for their stregdollars and see personal data :-(

**Comment by krestenlaust** [comment] 2023-08-22 07:51
Possibly duplicate of #286, but that's an old issue, so it's probably best to keep this open to keep it relevant.

**Comment by falkecarlsen** [comment] 2023-08-22 07:56
Duplicate of #286, and also duplicate of notice we often get from new users.

Consider that the purchasing system is built on trust. 
- If the aim is to get wares for free, they can just steal directly from the fridges.
- If the point is to access private information on the user, and they do it by _url-hacking_, [straffeloven §263](https://danskelove.dk/straffeloven/263) might apply.

To remedy this, both the ID's and the API needs to be changed. Furthermore, we lose a way to measure seniority for e.g. fastelavns-events if auto-inc IDs are lost.

People are welcome to open a PR with work to fix the above points, but *all* points must be considered for the fix to be accepted. Since this hasn't happened - or really been requested - for the past many years, I'll close this and parent issue.

**Closed by falkecarlsen** 2023-08-22 07:56 UTC

**Comment by krestenlaust** [comment] 2023-08-22 08:54
In general, I believe in the trust-system. It's a slippery slope if we begin locking down the system and reduce trust, and we move far away from the original goal of it simply being a digital representation of a paper for tallying, and overcomplicates the system.

With that said, I don't believe hiding the IDs would be a great challenge. As far as I know, the API is used in a very limited capacity, and most of the applications using it is under f-klubben management anyway. I'm not aware of how the easter event works, but it would still be possible to have a reverse lookup of usernames->ID. It would require some effort of both fappen and stregsystem though.

Though I'm just a first year student as well
