### ISSUE TITLE
Upgrade to python 3

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#36] opened 2017-03-22 17:43 UTC
Python 2.7 is reaching end of life, we should consider upgrading to python 3 if we are going to keep developing this version.

http://legacy.python.org/dev/peps/pep-0373/#id2

**Comment by VirtualSatai** [comment] 2017-03-22 17:51
Duplicate of #20

**Closed by VirtualSatai** 2017-03-22 17:51 UTC
