### ISSUE TITLE
Tag Support on Products (Soda, Caffeine, alcohol)

### ISSUE THREAD

**Issue by jones-g** [f-klubben/stregsystemet#34] opened 2017-03-22 15:48 UTC
See f-klubben/stregsystem#13 for more info

**Comment by Rene4100** [comment] 2017-10-13 08:19
Is this related or maybe even a duplicate of #80 ?

**Comment by DelusionalLogic** [comment] 2017-10-13 20:53
It sure looks like it. I'll go ahead and close it. Feel free to reopen if you have anything to add!

**Closed by DelusionalLogic** 2017-10-13 20:53 UTC
Labels: enhancement
